import fs from "fs";
import matter from "gray-matter";
import Link from "next/link";
import path from "path";
import { postFilePaths, POSTS_PATH } from "../utils/mdxUtils";

import Container from "../components/post/container";
import MoreStories from "../components/post/more-stories";
import HeroPost from "../components/post/hero-post";
import Intro from "../components/post/intro";
import Layout from "../components/layout";
// import { getAllPosts } from '../lib/api'
// import Head from 'next/head'
// import { CMS_NAME } from '../lib/constants'
// import Post from '../types/post'

export default function Post({ posts }) {
  return (
    <Layout>
      <h1>Home Page</h1>
      <p>
        Click the link below to navigate to a page generated by{" "}
        <code>next-mdx-remote</code>.
      </p>
      <ul>
        {posts.map((post) => (
          <li key={post.filePath}>
            <Link
              as={`/posts/${post.filePath.replace(/\.mdx?$/, "")}`}
              href={`/posts/[slug]`}
            >
              <a>{post.data.title}</a>
            </Link>
          </li>
        ))}
      </ul>
    </Layout>
  );
}

export function getStaticProps() {
  const posts = postFilePaths.map((filePath) => {
    const source = fs.readFileSync(path.join(POSTS_PATH, filePath));
    const { content, data } = matter(source);

    console.log(
      `content: ${content}, data: ${JSON.stringify(
        data
      )}, filepath: ${filePath}`
    );

    return {
      content,
      data,
      filePath,
    };
  });

  return { props: { posts } };
}
